routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function(){
    Route::redirect('/', 'users/login');
    Route::match(['get', 'post'],'login','login')->name('login');
    Route::get('logout','logout')->name('logout');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function (){

    Route::redirect('/','admin/dashboards/index');

    Route::group(['controller' => 'DashboardsController', 'prefix' => 'dashboards', 'as' => 'dashboards.'], function(){
        Route::redirect('/','dashboards/index');
        Route::get('index','index')->name('index');
        Route::get('counts','counts')->name('counts');
        Route::get('getTasks','getTasks')->name('getTasks');
    });

    Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function (){
        Route::redirect('/','users/index');
        Route::get('index','index')->name('index');
        Route::get('getUsers','getUsers')->name('getUsers');
        Route::get('bin','bin')->name('bin');
        Route::get('getUsersDeleted','getUsersDeleted')->name('getUsersDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'SeedsController', 'prefix' => 'seeds', 'as' => 'seeds.'], function (){
        Route::redirect('/','seeds/index');
        Route::get('index','index')->name('index');
        Route::get('getSeeds','getSeeds')->name('getSeeds');
        Route::get('bin','bin')->name('bin');
        Route::get('getSeedsDeleted','getSeedsDeleted')->name('getSeedsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}','view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'UnitsController', 'prefix' => 'units', 'as' => 'units.'], function (){
        Route::redirect('/','units/index');
        Route::get('index','index')->name('index');
        Route::get('getUnits','getUnits')->name('getUnits');
        Route::get('bin','bin')->name('bin');
        Route::get('getUnitsDeleted','getUnitsDeleted')->name('getUnitsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'CategoriesController', 'prefix' => 'categories', 'as' => 'categories.'], function (){
        Route::redirect('/','categories/index');
        Route::get('index','index')->name('index');
        Route::get('getCategories','getCategories')->name('getCategories');
        Route::get('bin','bin')->name('bin');
        Route::get('getCategoriesDeleted','getCategoriesDeleted')->name('getCategoriesDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'SuppliesController', 'prefix' => 'supplies', 'as' => 'supplies.'], function (){
        Route::redirect('/','supplies/index');
        Route::get('index','index')->name('index');
        Route::get('getSupplies','getSupplies')->name('getSupplies');
        Route::get('bin','bin')->name('bin');
        Route::get('getSuppliesDeleted','getSuppliesDeleted')->name('getSuppliesDeleted');
        Route::get('getSuppliesList','getSuppliesList')->name('getSuppliesList');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'PlantsController', 'prefix' => 'plants', 'as' => 'plants.'], function (){
        Route::redirect('/','plants/index');
        Route::get('index','index')->name('index');
        Route::get('getPlants','getPlants')->name('getPlants');
        Route::get('bin','bin')->name('bin');
        Route::get('getPlantsDeleted','getPlantsDeleted')->name('getPlantsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}','view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'TasksController', 'prefix' => 'tasks', 'as' => 'tasks.'], function (){
        Route::redirect('/','tasks/index');
        Route::get('getTasks/{plantId}','getTasks')->name('getTasks');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::post('isComplete/{id}/{isComplete}','isComplete')->name('isComplete');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
    });

    Route::group(['controller' => 'ExpensesController', 'prefix' => 'expenses', 'as' => 'expenses.'], function (){
        Route::redirect('/','expenses/index');
        Route::get('getExpenses/{plantId}','getExpenses')->name('getExpenses');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
    });

});

resources/views/element/admin/header.blade.php
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h5 class="m-b-10"></h5>
                </div>
            </div>
            <div class="col-md-4">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="javascript:void(0);">
                            <i class="fa fa-home"></i>
                        </a>
                    </li>
                    @foreach(explode('.', Route::currentRouteName()) as $row)
                        <li class="breadcrumb-item">
                            <a href="javascript:void(0);"> {{ucwords($row)}}</a>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/element/admin/navbar.blade.php
<nav class="navbar header-navbar pcoded-header">
    <div class="navbar-wrapper">
        <div class="navbar-logo">
            <a class="mobile-menu waves-effect waves-light" id="mobile-collapse" href="javascript:void(0);">
                <i class="ti-menu"></i>
            </a>
            <a href="javascript:void(0);">
                <img class="img-fluid" src="{{url('public/assets/images/logo.png')}}" loading="lazy" alt="Theme-Logo" />
            </a>
            <a class="mobile-options waves-effect waves-light">
                <i class="ti-more"></i>
            </a>
        </div>

        <div class="navbar-container container-fluid">
            <ul class="nav-left">
                <li>
                    <div class="sidebar_toggle"><a href="javascript:void(0)"><i class="ti-menu"></i></a></div>
                </li>
                <li>
                    <a href="javascript:void(0);" onclick="javascript:toggleFullScreen()" class="waves-effect waves-light">
                        <i class="ti-fullscreen"></i>
                    </a>
                </li>
            </ul>
            <ul class="nav-right">
                <li class="header-notification">
                    <a href="javascript:void(0);" class="waves-effect waves-light">
                        <i class="ti-bell"></i>
                        <span class="badge bg-c-red"></span>
                    </a>
                    <ul class="show-notification">
                        <li>
                            <h6>Notifications</h6>
                            <label class="label label-danger">New</label>
                        </li>
                        <li class="waves-effect waves-light">
                            <div class="media">
                                <img class="d-flex align-self-center img-radius" src="assets/images/avatar-2.jpg" alt="Generic placeholder image">
                                <div class="media-body">
                                    <h5 class="notification-user">John Doe</h5>
                                    <p class="notification-msg">Lorem ipsum dolor sit amet, consectetuer elit.</p>
                                    <span class="notification-time">30 minutes ago</span>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/element/admin/sidebar.blade.php
<nav class="pcoded-navbar">
    <div class="sidebar_toggle">
        <a href="javascript:void(0);">
            <i class="icon-close icons"></i
            ></a>
    </div>
    <div class="pcoded-inner-navbar main-menu">
        <div class="">
            <div class="main-menu-header">
                <img class="img-80 img-radius" src="{{url('public/img/logo.png')}}" style="object-fit: contain !important;" loading="lazy" alt="Default Logo">
                <div class="user-details">
                    <span id="more-details">
                        {{strtoupper(auth()->user()->name)}}
                        <i class="fa fa-caret-down"></i>
                    </span>
                </div>
            </div>

            <div class="main-menu-content">
                <ul>
                    <li class="more-details">
                        <a href="user-profile.html">
                            <i class="ti-user"></i>
                            View Profile
                        </a>
                        <a href="{{route('users.logout')}}">
                            <i class="ti-layout-sidebar-left"></i>
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="p-15 p-b-0">

        </div>
        <div class="pcoded-navigation-label" data-i18n="nav.category.navigation">Navigation</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="{{(request()->routeIs('admin.dashboards.index'))? 'active': null;}}">
                <a href="{{route('admin.dashboards.index')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Dashboard</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="{{(request()->routeIs('admin.users.index'))? 'active': null;}}">
                <a href="{{route('admin.users.index')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="ti-user"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Users</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="{{(request()->routeIs('admin.plants.index'))? 'active': null;}}">
                <a href="{{route('admin.plants.index')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="fa fa-pagelines"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Plants</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="{{(request()->routeIs('admin.seeds.index'))? 'active': null;}}">
                <a href="{{route('admin.seeds.index')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="fa fa-tree"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Seeds</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="{{(request()->routeIs('admin.supplies.index'))? 'active': null;}}">
                <a href="{{route('admin.supplies.index')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="ti-package"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Supplies</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>

            <li class="{{(request()->routeIs('admin.units.index'))? 'active': null;}}">
                <a href="{{route('admin.units.index')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="fa fa-balance-scale"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Units</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="{{(request()->routeIs('admin.categories.index'))? 'active': null;}}">
                <a href="{{route('admin.categories.index')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="ti-list"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Categories</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
        </ul>

        <div class="pcoded-navigation-label" data-i18n="nav.category.navigation">Bin</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="{{(request()->routeIs('admin.plants.bin'))? 'active': null;}}">
                <a href="{{route('admin.plants.bin')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="fa fa-pagelines"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Plants</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="{{(request()->routeIs('admin.seeds.bin'))? 'active': null;}}">
                <a href="{{route('admin.seeds.bin')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="fa fa-tree"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Seeds</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="{{(request()->routeIs('admin.supplies.bin'))? 'active': null;}}">
                <a href="{{route('admin.supplies.bin')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="ti-package"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Supplies</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>

            <li class="{{(request()->routeIs('admin.units.bin'))? 'active': null;}}">
                <a href="{{route('admin.units.bin')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="fa fa-balance-scale"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Units</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="{{(request()->routeIs('admin.categories.bin'))? 'active': null;}}">
                <a href="{{route('admin.categories.bin')}}" class="waves-effect waves-dark">
                    <span class="pcoded-micon">
                        <i class="ti-list"></i>
                        <b>D</b>
                    </span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Categories</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
        </ul>
    </div>
</nav>