routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function(){
    Route::redirect('/', 'users/login');
    Route::match(['get', 'post'],'login','login')->name('login');
    Route::get('logout','logout')->name('logout');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function (){

    Route::redirect('/','admin/dashboards/index');

    Route::group(['controller' => 'DashboardsController', 'prefix' => 'dashboards', 'as' => 'dashboards.'], function(){
        Route::redirect('/','dashboards/index');
        Route::get('index','index')->name('index');
        Route::get('counts','counts')->name('counts');
        Route::get('getTasks','getTasks')->name('getTasks');
    });

    Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function (){
        Route::redirect('/','users/index');
        Route::get('index','index')->name('index');
        Route::get('getUsers','getUsers')->name('getUsers');
        Route::get('bin','bin')->name('bin');
        Route::get('getUsersDeleted','getUsersDeleted')->name('getUsersDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'SeedsController', 'prefix' => 'seeds', 'as' => 'seeds.'], function (){
        Route::redirect('/','seeds/index');
        Route::get('index','index')->name('index');
        Route::get('getSeeds','getSeeds')->name('getSeeds');
        Route::get('bin','bin')->name('bin');
        Route::get('getSeedsDeleted','getSeedsDeleted')->name('getSeedsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}','view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'UnitsController', 'prefix' => 'units', 'as' => 'units.'], function (){
        Route::redirect('/','units/index');
        Route::get('index','index')->name('index');
        Route::get('getUnits','getUnits')->name('getUnits');
        Route::get('bin','bin')->name('bin');
        Route::get('getUnitsDeleted','getUnitsDeleted')->name('getUnitsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'CategoriesController', 'prefix' => 'categories', 'as' => 'categories.'], function (){
        Route::redirect('/','categories/index');
        Route::get('index','index')->name('index');
        Route::get('getCategories','getCategories')->name('getCategories');
        Route::get('bin','bin')->name('bin');
        Route::get('getCategoriesDeleted','getCategoriesDeleted')->name('getCategoriesDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'SuppliesController', 'prefix' => 'supplies', 'as' => 'supplies.'], function (){
        Route::redirect('/','supplies/index');
        Route::get('index','index')->name('index');
        Route::get('getSupplies','getSupplies')->name('getSupplies');
        Route::get('bin','bin')->name('bin');
        Route::get('getSuppliesDeleted','getSuppliesDeleted')->name('getSuppliesDeleted');
        Route::get('getSuppliesList','getSuppliesList')->name('getSuppliesList');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'PlantsController', 'prefix' => 'plants', 'as' => 'plants.'], function (){
        Route::redirect('/','plants/index');
        Route::get('index','index')->name('index');
        Route::get('getPlants','getPlants')->name('getPlants');
        Route::get('bin','bin')->name('bin');
        Route::get('getPlantsDeleted','getPlantsDeleted')->name('getPlantsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}','view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'TasksController', 'prefix' => 'tasks', 'as' => 'tasks.'], function (){
        Route::redirect('/','tasks/index');
        Route::get('getTasks/{plantId}','getTasks')->name('getTasks');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::post('isComplete/{id}/{isComplete}','isComplete')->name('isComplete');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
    });

    Route::group(['controller' => 'ExpensesController', 'prefix' => 'expenses', 'as' => 'expenses.'], function (){
        Route::redirect('/','expenses/index');
        Route::get('getExpenses/{plantId}','getExpenses')->name('getExpenses');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
    });

});

app/Http/Controllers/Admin/PlantsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Expense;
use App\Models\Plant;
use App\Models\Seed;
use App\Models\Tasks;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class PlantsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        return view('Admin.Plants.index');
    }

    public function getPlants(){
        $data = Plant::withoutTrashed()->with([
            'Users' => function($query){
                return $query->withTrashed()->get();
            },
            'Seeds' => function($query){
                return $query->withTrashed()->get();
            },
        ])->get();
        return response()->json(['data' => $data]);
    }

    public function bin(){
        return view('Admin.Plants.bin');
    }

    public function getPlantsDeleted(){
        $data = Plant::onlyTrashed()->with([
            'Users' => function($query){
                return $query->withTrashed()->get();
            },
            'Seeds' => function($query){
                return $query->withTrashed()->get();
            },
        ])->get();
        return response()->json(['data' => $data]);
    }

    public function add(Request $request){
        if($request->isMethod('post')){

            $plant = Plant::query()->make($request->all());

            $validator = $request->validate([
                'user_id' => ['required', 'numeric', Rule::exists('users','id')],
                'seed_id' => ['required', 'numeric', Rule::exists('seeds','id')],
                'budget' => ['required', 'numeric'],
                'quantity' => ['required', 'numeric'],
                'price' => ['required', 'numeric'],
                'total' => ['required', 'numeric'],
                'balance' => ['required', 'numeric'],
                'description' => ['required', 'max:4294967295'],
                'is_active' => ['required', 'numeric', Rule::in([0, 1])],
                'harvest_at' => ['required', 'date'],
                'harvested_at' => ['nullable', 'date'],
                'is_harvested' => ['required', 'numeric', Rule::in([0, 1])],
            ],[
                'user_id.required' => ucwords('no user authenticated'),
                'user_id.numeric' => ucwords('no user authenticated'),
                'user_id.exists' => ucwords('no user authenticated'),
                'seed_id.required' => ucwords('please select a seed'),
                'seed_id.numeric' => ucwords('please select a seed'),
                'seed_id.exists' => ucwords('please select a seed'),
                'budget.required' => ucwords('please fill out this field'),
                'budget.numeric' => ucwords('this field must be numeric value'),
                'quantity.required' => ucwords('please fill out this field'),
                'quantity.numeric' => ucwords('this field must be numeric value'),
                'price.required' => ucwords('please fill out this field'),
                'price.numeric' => ucwords('this field must be numeric value'),
                'total.required' => ucwords('please fill out this field'),
                'total.numeric' => ucwords('this field must be numeric value'),
                'balance.required' => ucwords('please fill out this field'),
                'balance.numeric' => ucwords('this field must be numeric value'),
                'description.required' => ucwords('please enter a description'),
                'description.max' => ucwords('this field must not exceed at 4294967295 characters'),
                'is_active.required' => ucwords('please select is active value'),
                'is_active.numeric' => ucwords('please select is active value'),
                'is_active.in' => ucwords('please select is active value'),
                'harvest_at.required' => ucwords('please fill out this field'),
                'harvest_at.date' => ucwords('this field must be date value'),
                'harvested_at.date' => ucwords('this field must be date value'),
                'is_harvested.required' => ucwords('please select is harvested value'),
                'is_harvested.numeric' => ucwords('please select is harvested value'),
                'is_harvested.in' => ucwords('please select is harvested value')
            ]);

            if($plant->save()){
                $result = ['message' => ucwords('the plant has been saved'), 'result' => ucwords('success'),
                    'redirect' => route('admin.plants.index')];
                return response()->json($result,200);
            }else{
                $result = ['message' => ucwords('the plant has not been saved'), 'result' => ucwords('error')];
                return response()->json($result,422);
            }

        }
        $seeds = Seed::withoutTrashed()
            ->orderBy('seed', 'ASC')
            ->where([
                ['is_active', '=', intval(1)]
            ])
            ->get()
            ->map(function ($query){
                return ['value' => ucwords($query->seed), 'key' => intval($query->id)];
            })->pluck('value', 'key');
        return view('Admin.Plants.add', compact('seeds'));
    }

    public function edit($id = null, Request $request){
        $plant = Plant::withoutTrashed()
            ->with([
                'Seeds' => function($query){
                    return $query->withTrashed()->get();
                },
                'Tasks' => function($query){
                    return $query->withTrashed()->get();
                },
                'Expenses' => function($query){
                    return $query->withTrashed()->get();
                },
            ])
            ->findOrFail($id);

        if($request->isMethod('post')){

            if(count($plant->tasks) || count($plant->expenses)){
                $result = ['message' => ucwords('the plant is already in progress'), 'result' => ucwords('info')];
                return response()->json($result,422);
            }

            $validator = $request->validate([
                'user_id' => ['required', 'numeric', Rule::exists('users','id')],
                'seed_id' => ['required', 'numeric', Rule::exists('seeds','id')],
                'budget' => ['required', 'numeric'],
                'quantity' => ['required', 'numeric'],
                'price' => ['required', 'numeric'],
                'total' => ['required', 'numeric'],
                'balance' => ['required', 'numeric'],
                'description' => ['required', 'max:4294967295'],
                'is_active' => ['required', 'numeric', Rule::in([0, 1])],
                'harvest_at' => ['required', 'date'],
                'harvested_at' => ['nullable', 'date'],
                'is_harvested' => ['required', 'numeric', Rule::in([0, 1])],
            ],[
                'user_id.required' => ucwords('no user authenticated'),
                'user_id.numeric' => ucwords('no user authenticated'),
                'user_id.exists' => ucwords('no user authenticated'),
                'seed_id.required' => ucwords('please select a seed'),
                'seed_id.numeric' => ucwords('please select a seed'),
                'seed_id.exists' => ucwords('please select a seed'),
                'budget.required' => ucwords('please fill out this field'),
                'budget.numeric' => ucwords('this field must be numeric value'),
                'quantity.required' => ucwords('please fill out this field'),
                'quantity.numeric' => ucwords('this field must be numeric value'),
                'price.required' => ucwords('please fill out this field'),
                'price.numeric' => ucwords('this field must be numeric value'),
                'total.required' => ucwords('please fill out this field'),
                'total.numeric' => ucwords('this field must be numeric value'),
                'balance.required' => ucwords('please fill out this field'),
                'balance.numeric' => ucwords('this field must be numeric value'),
                'description.required' => ucwords('please enter a description'),
                'description.max' => ucwords('this field must not exceed at 4294967295 characters'),
                'is_active.required' => ucwords('please select is active value'),
                'is_active.numeric' => ucwords('please select is active value'),
                'is_active.in' => ucwords('please select is active value'),
                'harvest_at.required' => ucwords('please fill out this field'),
                'harvest_at.date' => ucwords('this field must be date value'),
                'harvested_at.date' => ucwords('this field must be date value'),
                'is_harvested.required' => ucwords('please select is harvested value'),
                'is_harvested.numeric' => ucwords('please select is harvested value'),
                'is_harvested.in' => ucwords('please select is harvested value')
            ]);

            $plant->update($request->all());

            if($plant->save()){
                $result = ['message' => ucwords('the plant has been saved'), 'result' => ucwords('success'),
                    'redirect' => route('admin.plants.index')];
                return response()->json($result,200);
            }else{
                $result = ['message' => ucwords('the plant has not been saved'), 'result' => ucwords('error')];
                return response()->json($result,422);
            }

        }
        $seeds = Seed::withoutTrashed()
            ->orderBy('seed', 'ASC')
            ->where([
                ['is_active', '=', intval(1)]
            ])
            ->get()
            ->map(function ($query){
                return ['value' => ucwords($query->seed), 'key' => intval($query->id)];
            })->pluck('value', 'key');
        return view('Admin.Plants.edit', compact('plant', 'seeds'));
    }

resources/views/Admin/Plants/index.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[1]))
@section('content')

    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 d-flex justify-content-end align-items-center">
            <a href="{{route('admin.plants.add')}}" class="btn btn-primary rounded-0" title="New Plant">
                New Plant
            </a>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card">
                <div class="card-header">
                    <h5>Plants</h5>
                </div>
                <div class="card-block">
                    <div class="table-responsive">
                        <table id="datatable" class="table dt-responsive nowrap mt-5" style="width:100%">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Seed</th>
                                <th>Budget</th>
                                <th>Balance</th>
                                <th>Harvest At</th>
                                <th>Harvested At</th>
                                <th>Updated By</th>
                                <th>Updated At</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        'use strict';
        $(document).ready(function () {
            const baseurl = mainurl+'plants/';
            var url = '';
            var title = function () {
                return capitalize('Plant reports');
            };

            var datatable = $('#datatable');
            var table = datatable.DataTable({
                destroy:true,
                dom:'RlBfrtip',
                processing:true,
                responsive: true,
                serchDelay:3500,
                deferRender: true,
                stateSave: false,
                pagingType: 'full_numbers',
                order:[[0, 'asc']],
                lengthMenu:[100, 200, 500, 1000],
                ajax:{
                    url:baseurl+'getPlants',
                    method: 'GET',
                    dataType: 'JSON',
                    beforeSend: function (e) {

                    },
                    error:function (data, status, xhr) {
                        window.location.reload();
                    }
                },
                colReorder: {
                    allowReorder: true
                },
                buttons: [
                    {
                        extend: 'print',
                        title: 'Print',
                        text: 'Print',
                        attr:  {
                            id: 'print',
                            class:'btn btn-secondary rounded-0',
                        },
                        exportOptions: {
                            columns: [0,1,2,3,4,5,6,7,]
                        },
                        customize: function ( win ) {
                            $(win.document.body)
                                .css( 'font-size', '10px' )
                                .prepend('');
                            $(win.document.body).find( 'table tbody' )
                                .addClass( 'compact' )
                                .css( 'font-size', 'inherit' ).css({'background':'transparent'});
                        },
                        messageTop: function () {
                            return null;
                        },
                        messageBottom: function () {
                            return 'Printed At '+(moment().format('Y-MM-DD h:m A'));
                        },
                        footer:true
                    },
                    {
                        extend: 'excelHtml5',
                        attr:  {
                            id: 'excel',
                            class:'btn btn-success rounded-0',
                        },
                        title: title,
                        text: 'Excel',
                        tag: 'button',
                        exportOptions: {
                            columns: [0,1,2,3,4,5,6,7,]
                        },
                        action: function(e, dt, node, config) {
                            Swal.fire({
                                title:'Excel',
                                text:'Export To Excel?',
                                icon: 'question',
                                showCancelButton: true,
                                confirmButtonColor: '#3085d6',
                                cancelButtonColor: '#d33',
                                confirmButtonText: 'Yes'
                            }).then(function (result) {
                                if (result.isConfirmed) {
                                    setTimeout(function(){
                                        $.fn.dataTable.ext.buttons.excelHtml5.action.call(dt.button(this), e, dt, node, config);
                                    }, 1000);
                                }
                            });
                        },
                        messageTop: function () {
                            return null;
                        },
                        messageBottom: function () {
                            return 'Printed At '+(moment().format('Y-MM-DD h:m A'));
                        },
                        footer:true
                    },
                    {
                        extend: 'pdfHtml5',
                        attr:  {
                            id: 'pdf',
                            class:'btn btn-danger rounded-0',
                        },
                        text: 'PDF',
                        title: title,
                        tag: 'button',
                        orientation: 'landscape',
                        pageSize: 'LEGAL',
                        exportOptions: {
                            columns: [0,1,2,3,4,5,6,7,]
                        },
                        action: function(e, dt, node, config) {
                            Swal.fire({
                                title:'PDF',
                                text:'Export To PDF?',
                                icon: 'question',
                                showCancelButton: true,
                                confirmButtonColor: '#3085d6',
                                cancelButtonColor: '#d33',
                                confirmButtonText: 'Yes'
                            }).then(function (result) {
                                if (result.isConfirmed) {
                                    setTimeout(function(){
                                        $.fn.dataTable.ext.buttons.pdfHtml5.action.call(dt.button(this), e, dt, node, config);
                                    }, 1000);
                                }
                            });
                        },
                        customize: function(doc) {
                            doc.pageMargins = [2, 2, 2, 2 ];
                            doc.content[1].table.widths = Array(doc.content[1].table.body[0].length + 1).join('*').split('');
                            doc.styles.tableHeader.fontSize = 7;
                            doc.styles.tableBodyEven.fontSize = 7;
                            doc.styles.tableBodyOdd.fontSize = 7;
                            doc.styles.tableFooter.fontSize = 7;
                        },
                        download: 'open',
                        messageTop: function () {
                            return null;
                        },
                        messageBottom: function () {
                            return 'Printed At '+(moment().format('Y-MM-DD h:m A'));
                        },
                        footer:true
                    },
                ],
                columnDefs: [
                    {
                        targets: [0],
                        data: null,
                        render: function ( data, type, full, meta ) {
                            const row = meta.row;
                            return  row+1;
                        }
                    },
                    {
                        targets: [1],
                        data: null,
                        render: function(data,type,row,meta){
                            var isActive = (row.is_active)? 'Active': 'Inactive';
                            return row.seeds.seed + ' ('+(isActive)+')';
                        }
                    },
                    {
                        targets: [2],
                        data: null,
                        render: function(data,type,row,meta){
                            return (new Intl.NumberFormat().format(parseFloat(row.budget)));
                        }
                    },
                    {
                        targets: [3],
                        data: null,
                        render: function(data,type,row,meta){
                            return (new Intl.NumberFormat().format(parseFloat(row.balance)));
                        }
                    },
                    {
                        targets: [4],
                        data: null,
                        render: function(data,type,row,meta){
                            return moment(row.harvest_at).format('Y-MM-DD');
                        }
                    },
                    {
                        targets: [5],
                        data: null,
                        render: function(data,type,row,meta){
                            return (row.harvested_at)? moment(row.harvested_at).format('Y-MM-DD'): '-';
                        }
                    },
                    {
                        targets: [7],
                        data: null,
                        render: function(data,type,row,meta){
                            return moment(row.updated_at).format('Y-MM-DD hh:mm A');
                        }
                    },
                    {
                        targets: [8],
                        data: null,
                        orderable:false,
                        searchable:false,
                        render: function(data,type,row,meta){
                            return '<a data-id="'+(parseInt(row.id))+'" class="btn btn-sm btn-info rounded-0 text-white view" title="View">View</a> | '+
                                '<a data-id="'+(parseInt(row.id))+'" class="btn btn-sm btn-danger rounded-0 text-white delete" title="Delete">Delete</a>';
                        }
                    }
                ],
                columns: [
                    { data: 'id'},
                    { data: 'seeds.seed'},
                    { data: 'budget'},
                    { data: 'balance'},
                    { data: 'harvest_at'},
                    { data: 'harvested_at'},
                    { data: 'users.name'},
                    { data: 'updated_at'},
                    { data: 'id'},
                ]
            });

            datatable.on('click','.view',function (e) {
                e.preventDefault();
                var dataId = $(this).attr('data-id');
                var href = baseurl+'view/'+(dataId);
                Turbolinks.visit(href, {action: 'advance'});
            });

            datatable.on('click','.delete',function (e) {
                e.preventDefault();
                var dataId = $(this).attr('data-id');
                var href = baseurl+'delete/'+(parseInt(dataId));
                Swal.fire({
                    title: 'Delete Data',
                    text: 'Are You Sure?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes'
                }).then(function (result) {
                    if (result.isConfirmed) {
                        $.ajax({
                            url:href,
                            type: 'DELETE',
                            method: 'DELETE',
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            dataType:'JSON',
                            beforeSend: function (e) {
                                Swal.fire({
                                    icon: 'info',
                                    title: null,
                                    text: 'Please Wait!...',
                                    allowOutsideClick: false,
                                    showConfirmButton: false,
                                    timerProgressBar: false,
                                    didOpen: function () {
                                        Swal.showLoading();
                                    }
                                });
                            },
                        }).done(function (data, status, xhr) {
                            swal('success', null, data.message);
                            table.ajax.reload(null, false);
                        }).fail(function (data, status, xhr) {
                            swal('error', 'Error', data.responseJSON.message);
                        });
                    }
                });
            });

        });
    </script>

@endsection