routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function(){
    Route::redirect('/', 'users/login');
    Route::match(['get', 'post'],'login','login')->name('login');
    Route::get('logout','logout')->name('logout');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function (){

    Route::redirect('/','admin/dashboards/index');

    Route::group(['controller' => 'DashboardsController', 'prefix' => 'dashboards', 'as' => 'dashboards.'], function(){
        Route::redirect('/','dashboards/index');
        Route::get('index','index')->name('index');
        Route::get('counts','counts')->name('counts');
        Route::get('getTasks','getTasks')->name('getTasks');
    });

    Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function (){
        Route::redirect('/','users/index');
        Route::get('index','index')->name('index');
        Route::get('getUsers','getUsers')->name('getUsers');
        Route::get('bin','bin')->name('bin');
        Route::get('getUsersDeleted','getUsersDeleted')->name('getUsersDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'SeedsController', 'prefix' => 'seeds', 'as' => 'seeds.'], function (){
        Route::redirect('/','seeds/index');
        Route::get('index','index')->name('index');
        Route::get('getSeeds','getSeeds')->name('getSeeds');
        Route::get('bin','bin')->name('bin');
        Route::get('getSeedsDeleted','getSeedsDeleted')->name('getSeedsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}','view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'UnitsController', 'prefix' => 'units', 'as' => 'units.'], function (){
        Route::redirect('/','units/index');
        Route::get('index','index')->name('index');
        Route::get('getUnits','getUnits')->name('getUnits');
        Route::get('bin','bin')->name('bin');
        Route::get('getUnitsDeleted','getUnitsDeleted')->name('getUnitsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'CategoriesController', 'prefix' => 'categories', 'as' => 'categories.'], function (){
        Route::redirect('/','categories/index');
        Route::get('index','index')->name('index');
        Route::get('getCategories','getCategories')->name('getCategories');
        Route::get('bin','bin')->name('bin');
        Route::get('getCategoriesDeleted','getCategoriesDeleted')->name('getCategoriesDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'SuppliesController', 'prefix' => 'supplies', 'as' => 'supplies.'], function (){
        Route::redirect('/','supplies/index');
        Route::get('index','index')->name('index');
        Route::get('getSupplies','getSupplies')->name('getSupplies');
        Route::get('bin','bin')->name('bin');
        Route::get('getSuppliesDeleted','getSuppliesDeleted')->name('getSuppliesDeleted');
        Route::get('getSuppliesList','getSuppliesList')->name('getSuppliesList');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'PlantsController', 'prefix' => 'plants', 'as' => 'plants.'], function (){
        Route::redirect('/','plants/index');
        Route::get('index','index')->name('index');
        Route::get('getPlants','getPlants')->name('getPlants');
        Route::get('bin','bin')->name('bin');
        Route::get('getPlantsDeleted','getPlantsDeleted')->name('getPlantsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}','view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'TasksController', 'prefix' => 'tasks', 'as' => 'tasks.'], function (){
        Route::redirect('/','tasks/index');
        Route::get('getTasks/{plantId}','getTasks')->name('getTasks');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::post('isComplete/{id}/{isComplete}','isComplete')->name('isComplete');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
    });

    Route::group(['controller' => 'ExpensesController', 'prefix' => 'expenses', 'as' => 'expenses.'], function (){
        Route::redirect('/','expenses/index');
        Route::get('getExpenses/{plantId}','getExpenses')->name('getExpenses');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
    });

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
        'is_admin',
        'is_active',
        'token',
        'remember_token',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'token',
        'remember_token',
    ];

    protected function setPasswordAttribute($value){
        return $this->attributes['password'] = Hash::make($value);
    }

    public function Seeds(){
        return $this->hasMany(Seed::class,'user_id','id');
    }

    public function Units(){
        return $this->hasMany(Unit::class,'user_id','id');
    }

    public function Categories(){
        return $this->hasMany(Category::class,'user_id','id');
    }

    public function Supplies(){
        return $this->hasMany(Supply::class,'user_id','id');
    }

    public function Plants(){
        return $this->hasMany(Plant::class,'user_id','id');
    }

    public function Tasks(){
        return $this->hasMany(Tasks::class,'user_id','id');
    }

    public function Expenses(){
        return $this->hasMany(Expense::class,'user_id','id');
    }

}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class UsersController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        return view('Admin.Users.index');
    }

    public function getUsers(){
        $data = User::withoutTrashed()->get();
        return response()->json(['data' => $data]);
    }

    public function bin(){
        return view('Admin.Users.bin');
    }

    public function getUsersDeleted(){
        $data = User::onlyTrashed()->get();
        return response()->json(['data' => $data]);
    }

    public function add(Request $request){
        if($request->isMethod('post')){

            $user = User::query()->make($request->all());

            $validator = $request->validate([
                'name' => ['required', 'max:255'],
                'username' => ['required', 'max:255', Rule::unique('users','username')],
                'email' => ['required', 'email', 'max:255', Rule::unique('users','email')],
                'password' => ['required', 'max:255', 'min:6'],
                'confirm_password' => ['required', 'max:255', 'same:password', 'min:6'],
                'is_admin' => ['required', 'numeric', Rule::in([0, 1])],
                'is_active' => ['required', 'numeric', Rule::in([0, 1])],
                'token' => ['required', 'max:255'],
            ],[
                'name.required' => ucwords('please fill out this field'),
                'name.max' => ucwords('this field must not exceed at 255 characters'),
                'username.required' => ucwords('please fill out this field'),
                'username.max' => ucwords('this field must not exceed at 255 characters'),
                'username.unique' => ucwords('this username is already exists'),
                'email.required' => ucwords('please fill out this field'),
                'email.email' => ucwords('please enter valid email'),
                'email.max' => ucwords('this field must not exceed at 255 characters'),
                'email.unique' => ucwords('this email is already exists'),
                'password.required' => ucwords('please fill out this field'),
                'password.max' => ucwords('this field must not exceed at 255 characters'),
                'password.min' => ucwords('this field must have 6 characters'),
                'confirm_password.required' => ucwords('please fill out this field'),
                'confirm_password.max' => ucwords('this field must not exceed at 255 characters'),
                'confirm_password.same' => ucwords('confirm password do not matched'),
                'confirm_password.min' => ucwords('this field must have 6 characters'),
                'is_admin.required' => ucwords('please select is admin'),
                'is_admin.numeric' => ucwords('please select is admin'),
                'is_admin.in' => ucwords('please select is admin'),
                'is_active.required' => ucwords('please select is active'),
                'is_active.numeric' => ucwords('please select is active'),
                'is_active.in' => ucwords('please select is active'),
                'token.required' => ucwords('please fill out this field'),
                'token.max' => ucwords('this field must not exceed at 255 characters'),
            ]);

            $user->token = uniqid().uniqid();

            if($user->save()){
                $result = ['message' => ucwords('the user has been saved'), 'result' => ucwords('success'),
                    'redirect' => route('admin.users.index')];
                return response()->json($result,200);
            }else{
                $result = ['message' => ucwords('the user has not been saved'), 'result' => ucwords('error')];
                return response()->json($result,422);
            }

        }
        return view('Admin.Users.add');
    }

    public function edit($id = null, Request $request){
        $user = User::withoutTrashed()->findOrFail($id);
        if($request->isMethod('post')){

            $validator = $request->validate([
                'name' => ['required', 'max:255'],
                'username' => ['required', 'max:255', Rule::unique('users','username')->ignore($user->id)],
                'email' => ['required', 'email', 'max:255', Rule::unique('users','email')->ignore($user->id)],
                'password' => ['required', 'max:255', 'min:6'],
                'confirm_password' => ['required', 'max:255', 'same:password', 'min:6'],
                'is_admin' => ['required', 'numeric', Rule::in([0, 1])],
                'is_active' => ['required', 'numeric', Rule::in([0, 1])],
                'token' => ['required', 'max:255'],
            ],[
                'name.required' => ucwords('please fill out this field'),
                'name.max' => ucwords('this field must not exceed at 255 characters'),
                'username.required' => ucwords('please fill out this field'),
                'username.max' => ucwords('this field must not exceed at 255 characters'),
                'username.unique' => ucwords('this username is already exists'),
                'email.required' => ucwords('please fill out this field'),
                'email.email' => ucwords('please enter valid email'),
                'email.max' => ucwords('this field must not exceed at 255 characters'),
                'email.unique' => ucwords('this email is already exists'),
                'password.required' => ucwords('please fill out this field'),
                'password.max' => ucwords('this field must not exceed at 255 characters'),
                'password.min' => ucwords('this field must have 6 characters'),
                'confirm_password.required' => ucwords('please fill out this field'),
                'confirm_password.max' => ucwords('this field must not exceed at 255 characters'),
                'confirm_password.same' => ucwords('confirm password do not matched'),
                'confirm_password.min' => ucwords('this field must have 6 characters'),
                'is_admin.required' => ucwords('please select is admin'),
                'is_admin.numeric' => ucwords('please select is admin'),
                'is_admin.in' => ucwords('please select is admin'),
                'is_active.required' => ucwords('please select is active'),
                'is_active.numeric' => ucwords('please select is active'),
                'is_active.in' => ucwords('please select is active'),
                'token.required' => ucwords('please fill out this field'),
                'token.max' => ucwords('this field must not exceed at 255 characters'),
            ]);

            $user->update($request->all());

            $user->token = uniqid().uniqid();

            if($user->save()){
                $result = ['message' => ucwords('the user has been saved'), 'result' => ucwords('success'),
                    'redirect' => route('admin.users.index')];
                return response()->json($result,200);
            }else{
                $result = ['message' => ucwords('the user has not been saved'), 'result' => ucwords('error')];
                return response()->json($result,422);
            }

        }
        return view('Admin.Users.edit', compact('user'));
    }

    public function delete($id = null){
        $user = User::withoutTrashed()->findOrFail($id);
        if($user->delete()){
            $result = ['message' => ucwords('the user has been deleted'), 'result' => ucwords('success')];
            return response()->json($result,200);
        }else{
            $result = ['message' => ucwords('the user has not been deleted'), 'result' => ucwords('error')];
            return response()->json($result,422);
        }
    }

    public function restore($id = null){
        $user = User::onlyTrashed()->findOrFail($id);
        if($user->restore()){
            $result = ['message' => ucwords('the user has been restored'), 'result' => ucwords('success')];
            return response()->json($result,200);
        }else{
            $result = ['message' => ucwords('the user has not been restored'), 'result' => ucwords('error')];
            return response()->json($result,422);
        }
    }

    public function forceDelete($id = null){
        $user = User::onlyTrashed()->findOrFail($id);
        if($user->forceDelete()){
            $result = ['message' => ucwords('the user has been deleted'), 'result' => ucwords('success')];
            return response()->json($result,200);
        }else{
            $result = ['message' => ucwords('the user has not been deleted'), 'result' => ucwords('error')];
            return response()->json($result,422);
        }
    }

}

resources/views/Admin/Users/index.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[1]))
@section('content')

    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 d-flex justify-content-end align-items-center">
            <a href="{{route('admin.users.add')}}" class="btn btn-primary rounded-0" title="New User">
                New User
            </a>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card">
                <div class="card-header">
                    <h5>Users</h5>
                </div>
                <div class="card-block">
                    <div class="table-responsive">
                        <table id="datatable" class="table dt-responsive nowrap mt-5" style="width:100%">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Updated At</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        'use strict';
        $(document).ready(function () {
            const baseurl = mainurl+'users/';
            var url = '';
            var title = function () {
                return capitalize('user reports');
            };

            var datatable = $('#datatable');
            var table = datatable.DataTable({
                destroy:true,
                dom:'RlBfrtip',
                processing:true,
                responsive: true,
                serchDelay:3500,
                deferRender: true,
                pagingType: 'full_numbers',
                order:[[0, 'asc']],
                lengthMenu:[100, 200, 500, 1000],
                ajax:{
                    url:baseurl+'getUsers',
                    method: 'GET',
                    dataType: 'JSON',
                    beforeSend: function (e) {

                    },
                    error:function (data, status, xhr) {
                        window.location.reload();
                    }
                },
                colReorder: {
                    allowReorder: true
                },
                buttons: [
                    {
                        extend: 'print',
                        title: 'Print',
                        text: 'Print',
                        attr:  {
                            id: 'print',
                            class:'btn btn-secondary rounded-0',
                        },
                        exportOptions: {
                            columns: [0,1,2,3,4,]
                        },
                        customize: function ( win ) {
                            $(win.document.body)
                                .css( 'font-size', '10px' )
                                .prepend('');
                            $(win.document.body).find( 'table tbody' )
                                .addClass( 'compact' )
                                .css( 'font-size', 'inherit' ).css({'background':'transparent'});
                        },
                        messageTop: function () {
                            return null;
                        },
                        messageBottom: function () {
                            return 'Printed At '+(moment().format('Y-MM-DD h:m A'));
                        },
                        footer:true
                    },
                    {
                        extend: 'excelHtml5',
                        attr:  {
                            id: 'excel',
                            class:'btn btn-success rounded-0',
                        },
                        title: title,
                        text: 'Excel',
                        tag: 'button',
                        exportOptions: {
                            columns: [0,1,2,3,4,]
                        },
                        action: function(e, dt, node, config) {
                            Swal.fire({
                                title:'Excel',
                                text:'Export To Excel?',
                                icon: 'question',
                                showCancelButton: true,
                                confirmButtonColor: '#3085d6',
                                cancelButtonColor: '#d33',
                                confirmButtonText: 'Yes'
                            }).then(function (result) {
                                if (result.isConfirmed) {
                                    setTimeout(function(){
                                        $.fn.dataTable.ext.buttons.excelHtml5.action.call(dt.button(this), e, dt, node, config);
                                    }, 1000);
                                }
                            });
                        },
                        messageTop: function () {
                            return null;
                        },
                        messageBottom: function () {
                            return 'Printed At '+(moment().format('Y-MM-DD h:m A'));
                        },
                        footer:true
                    },
                    {
                        extend: 'pdfHtml5',
                        attr:  {
                            id: 'pdf',
                            class:'btn btn-danger rounded-0',
                        },
                        text: 'PDF',
                        title: title,
                        tag: 'button',
                        orientation: 'landscape',
                        pageSize: 'LEGAL',
                        exportOptions: {
                            columns: [0,1,2,3,4,]
                        },
                        action: function(e, dt, node, config) {
                            Swal.fire({
                                title:'PDF',
                                text:'Export To PDF?',
                                icon: 'question',
                                showCancelButton: true,
                                confirmButtonColor: '#3085d6',
                                cancelButtonColor: '#d33',
                                confirmButtonText: 'Yes'
                            }).then(function (result) {
                                if (result.isConfirmed) {
                                    setTimeout(function(){
                                        $.fn.dataTable.ext.buttons.pdfHtml5.action.call(dt.button(this), e, dt, node, config);
                                    }, 1000);
                                }
                            });
                        },
                        customize: function(doc) {
                            doc.pageMargins = [2, 2, 2, 2 ];
                            doc.content[1].table.widths = Array(doc.content[1].table.body[0].length + 1).join('*').split('');
                            doc.styles.tableHeader.fontSize = 7;
                            doc.styles.tableBodyEven.fontSize = 7;
                            doc.styles.tableBodyOdd.fontSize = 7;
                            doc.styles.tableFooter.fontSize = 7;
                        },
                        download: 'open',
                        messageTop: function () {
                            return null;
                        },
                        messageBottom: function () {
                            return 'Printed At '+(moment().format('Y-MM-DD h:m A'));
                        },
                        footer:true
                    },
                ],
                columnDefs: [
                    {
                        targets: [0],
                        data: null,
                        render: function ( data, type, full, meta ) {
                            const row = meta.row;
                            return  row+1;
                        }
                    },
                    {
                        targets: [4],
                        data: null,
                        render: function(data,type,row,meta){
                            return moment(row.updated_at).format('Y-MM-DD hh:mm A');
                        }
                    },
                    {
                        targets: [5],
                        data: null,
                        orderable:false,
                        searchable:false,
                        render: function(data,type,row,meta){
                            return '<a data-id="'+(parseInt(row.id))+'" class="btn btn-sm btn-primary rounded-0 text-white edit" title="Edit">Edit</a> | '+
                                '<a data-id="'+(parseInt(row.id))+'" class="btn btn-sm btn-danger rounded-0 text-white delete" title="Delete">Delete</a>';
                        }
                    }
                ],
                columns: [
                    { data: 'id'},
                    { data: 'name'},
                    { data: 'username'},
                    { data: 'email'},
                    { data: 'updated_at'},
                    { data: 'id'},
                ]
            });

            datatable.on('click','.edit',function (e) {
                e.preventDefault();
                var dataId = $(this).attr('data-id');
                var href = baseurl+'edit/'+(dataId);
                Turbolinks.visit(href, {action: 'advance'});
            });

            datatable.on('click','.delete',function (e) {
                e.preventDefault();
                var dataId = $(this).attr('data-id');
                var href = baseurl+'delete/'+(parseInt(dataId));
                Swal.fire({
                    title: 'Delete Data',
                    text: 'Are You Sure?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes'
                }).then(function (result) {
                    if (result.isConfirmed) {
                        $.ajax({
                            url:href,
                            type: 'DELETE',
                            method: 'DELETE',
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            dataType:'JSON',
                            beforeSend: function (e) {
                                Swal.fire({
                                    icon: 'info',
                                    title: null,
                                    text: 'Please Wait!...',
                                    allowOutsideClick: false,
                                    showConfirmButton: false,
                                    timerProgressBar: false,
                                    didOpen: function () {
                                        Swal.showLoading();
                                    }
                                });
                            },
                        }).done(function (data, status, xhr) {
                            swal('success', null, data.message);
                            table.ajax.reload(null, false);
                        }).fail(function (data, status, xhr) {
                            swal('error', 'Error', data.responseJSON.message);
                        });
                    }
                });
            });

        });
    </script>

@endsection