routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function(){
    Route::redirect('/', 'users/login');
    Route::match(['get', 'post'],'login','login')->name('login');
    Route::get('logout','logout')->name('logout');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function (){

    Route::redirect('/','admin/dashboards/index');

    Route::group(['controller' => 'DashboardsController', 'prefix' => 'dashboards', 'as' => 'dashboards.'], function(){
        Route::redirect('/','dashboards/index');
        Route::get('index','index')->name('index');
        Route::get('counts','counts')->name('counts');
        Route::get('getTasks','getTasks')->name('getTasks');
    });

    Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function (){
        Route::redirect('/','users/index');
        Route::get('index','index')->name('index');
        Route::get('getUsers','getUsers')->name('getUsers');
        Route::get('bin','bin')->name('bin');
        Route::get('getUsersDeleted','getUsersDeleted')->name('getUsersDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'SeedsController', 'prefix' => 'seeds', 'as' => 'seeds.'], function (){
        Route::redirect('/','seeds/index');
        Route::get('index','index')->name('index');
        Route::get('getSeeds','getSeeds')->name('getSeeds');
        Route::get('bin','bin')->name('bin');
        Route::get('getSeedsDeleted','getSeedsDeleted')->name('getSeedsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}','view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'UnitsController', 'prefix' => 'units', 'as' => 'units.'], function (){
        Route::redirect('/','units/index');
        Route::get('index','index')->name('index');
        Route::get('getUnits','getUnits')->name('getUnits');
        Route::get('bin','bin')->name('bin');
        Route::get('getUnitsDeleted','getUnitsDeleted')->name('getUnitsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'CategoriesController', 'prefix' => 'categories', 'as' => 'categories.'], function (){
        Route::redirect('/','categories/index');
        Route::get('index','index')->name('index');
        Route::get('getCategories','getCategories')->name('getCategories');
        Route::get('bin','bin')->name('bin');
        Route::get('getCategoriesDeleted','getCategoriesDeleted')->name('getCategoriesDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'SuppliesController', 'prefix' => 'supplies', 'as' => 'supplies.'], function (){
        Route::redirect('/','supplies/index');
        Route::get('index','index')->name('index');
        Route::get('getSupplies','getSupplies')->name('getSupplies');
        Route::get('bin','bin')->name('bin');
        Route::get('getSuppliesDeleted','getSuppliesDeleted')->name('getSuppliesDeleted');
        Route::get('getSuppliesList','getSuppliesList')->name('getSuppliesList');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'PlantsController', 'prefix' => 'plants', 'as' => 'plants.'], function (){
        Route::redirect('/','plants/index');
        Route::get('index','index')->name('index');
        Route::get('getPlants','getPlants')->name('getPlants');
        Route::get('bin','bin')->name('bin');
        Route::get('getPlantsDeleted','getPlantsDeleted')->name('getPlantsDeleted');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['get', 'post'],'edit/{id}','edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}','view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'TasksController', 'prefix' => 'tasks', 'as' => 'tasks.'], function (){
        Route::redirect('/','tasks/index');
        Route::get('getTasks/{plantId}','getTasks')->name('getTasks');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::post('isComplete/{id}/{isComplete}','isComplete')->name('isComplete');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
    });

    Route::group(['controller' => 'ExpensesController', 'prefix' => 'expenses', 'as' => 'expenses.'], function (){
        Route::redirect('/','expenses/index');
        Route::get('getExpenses/{plantId}','getExpenses')->name('getExpenses');
        Route::match(['get', 'post'],'add','add')->name('add');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
    });

});

app/Http/Controllers/Admin/ExpensesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Expense;
use App\Models\Plant;
use App\Models\Supply;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class ExpensesController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function getExpenses($plantId = null){
        $data = Expense::withoutTrashed()
            ->with([
                'Supplies' => function($query){
                    return $query->withTrashed()->get();
                },
                'Users' => function($query){
                    return $query->withTrashed()->get();
                }
            ])
            ->where([
                ['plant_id', '=', intval($plantId)]
            ])
            ->get();
        return response()->json(['data' => $data]);
    }

    public function add(Request $request){
        $plant = Plant::withoutTrashed()->findOrFail($request->query('plantId'));
        if($request->isMethod('post')){

            $validator = $request->validate([
                'user_id' => ['required', 'numeric', Rule::exists('users','id')],
                'plant_id' => ['required', 'numeric', Rule::exists('plants','id')],
                'supply_id' => ['required', 'numeric', Rule::exists('supplies','id')],
                'balance' => ['required', 'numeric'],
                'quantity' => ['required', 'numeric'],
                'price' => ['required', 'numeric'],
                'total' => ['required', 'numeric'],
                'total_balance' => ['required', 'numeric'],
                'remarks' => ['required', 'max:4294967295'],
                'is_task' => ['required', 'numeric', Rule::in([0, 1])]
            ],[
                'user_id.required' => ucwords('no user authenticated'),
                'user_id.numeric' => ucwords('no user authenticated'),
                'user_id.exists' => ucwords('no user authenticated'),
                'plant_id.required' => ucwords('please select a plant'),
                'plant_id.numeric' => ucwords('please select a plant'),
                'plant_id.exists' => ucwords('please select a plant'),
                'supply_id.required' => ucwords('please enter a supply'),
                'supply_id.numeric' => ucwords('please enter a supply'),
                'supply_id.exists' => ucwords('please enter a supply'),
                'balance.required' => ucwords('please fill out this field'),
                'balance.numeric' => ucwords('this field must be numeric value'),
                'quantity.required' => ucwords('please fill out this field'),
                'quantity.numeric' => ucwords('this field must be numeric value'),
                'price.required' => ucwords('please fill out this field'),
                'price.numeric' => ucwords('this field must be numeric value'),
                'total.required' => ucwords('please fill out this field'),
                'total.numeric' => ucwords('this field must be numeric value'),
                'total_balance.required' => ucwords('please fill out this field'),
                'total_balance.numeric' => ucwords('this field must be numeric value'),
                'remarks.required' => ucwords('please fill out this field'),
                'remarks.max' => ucwords('this field must nox exceed at 4294967295 characters'),
                'is_task.required' => ucwords('please select is task'),
                'is_task.numeric' => ucwords('please select is task'),
                'is_task.in' => ucwords('please select is task'),
            ]);

            $expense = Expense::query()->make($request->all());
            $supply = Supply::withoutTrashed()->findOrFail($request->input('supply_id'));

            $total = doubleval($supply->price) * intval($request->input('quantity'));
            $balance = $plant->balance;
            $total_balance = doubleval($balance) - doubleval($total);

            $expense->price = doubleval($supply->price);
            $expense->total = doubleval($total);
            $expense->balance = doubleval($balance);
            $expense->total_balance = doubleval($total_balance);

            $plant->balance = doubleval($total_balance);

            if($expense->save() && $plant->save()){
                $result = ['message' => ucwords('the expense has been saved'), 'result' => ucwords('success'),
                    'redirect' => route('admin.plants.view',['id' => intval($plant->id)])];
                return response()->json($result,200);
            }else{
                $result = ['message' => ucwords('the expense has not been saved'), 'result' => ucwords('error')];
                return response()->json($result,422);
            }

        }
        return view('Admin.Expenses.add', compact('plant'));
    }

    public function delete($id = null){
        $expense = Expense::withTrashed()->findOrFail($id);
        $plant = Plant::withoutTrashed()->findOrFail($expense->plant_id);

        $total = $expense->total;
        $balance = doubleval($plant->balance) + doubleval($total);

        $plant->balance = doubleval($balance);

        if($expense->forceDelete() && $plant->save()){
            $result = ['message' => ucwords('the expense has been deleted'), 'result' => ucwords('success')];
            return response()->json($result,200);
        }else{
            $result = ['message' => ucwords('the expense has not been deleted'), 'result' => ucwords('error')];
            return response()->json($result,422);
        }
    }

}

resources/views/Admin/Expenses/add.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[1]))
@section('content')

    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 d-flex justify-content-end align-items-center">
            <a href="{{route('admin.supplies.index')}}" class="btn btn-primary rounded-0" title="Return">
                Return
            </a>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card">
                <div class="card-header">
                    <h5>Expense Form</h5>
                </div>
                <form class="card-block" method="post" enctype="multipart/form-data" id="form">
                    @csrf
                    <div class="row">

                        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
                            <label for="supply">Supply</label>
                            <input type="text" name="supply" class="form-control" id="supply" placeholder="Supply" pattern="(.){1,}" title="{{ucwords('please fill out this field')}}" autocomplete="off" required>
                            <small class="mt-2"></small>
                        </div>

                        <div class="col-sm-12 col-md-4 col-lg-4 mt-3">
                            <label for="price">Price</label>
                            <input type="number" name="price" class="form-control" id="price" placeholder="Price" pattern="([0,9]){1,}" title="{{ucwords('please fill out this field')}}" min="1" autocomplete="off" required>
                            <small class="mt-2"></small>
                        </div>

                        <div class="col-sm-12 col-md-4 col-lg-4 mt-3">
                            <label for="quantity">Quantity</label>
                            <input type="number" name="quantity" class="form-control" id="quantity" placeholder="Quantity" pattern="([0,9]){1,}" title="{{ucwords('please fill out this field')}}" min="1" autocomplete="off" required>
                            <small class="mt-2"></small>
                        </div>

                        <div class="col-sm-12 col-md-4 col-lg-4 mt-3">
                            <label for="total">Total</label>
                            <input type="number" name="total" class="form-control" id="total" placeholder="Total" pattern="([0,9]){1,}" title="{{ucwords('please fill out this field')}}" min="1" autocomplete="off" readonly required>
                            <small class="mt-2"></small>
                        </div>

                        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
                            <label for="remarks">Remarks</label>
                            <textarea name="remarks" class="form-control" id="remarks" placeholder="Remarks" pattern="(.){1,}" title="{{ucwords('please fill out this field')}}" autocomplete="off" required cols="30" rows="10">-</textarea>
                            <small class="mt-2"></small>
                        </div>

                        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
                            <div class="icheck-primary d-inline">
                                <input type="checkbox" id="task">
                                <label for="task">Task</label>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-12 d-flex justify-content-end align-items-center">
                            <input type="hidden" name="is_task" id="is-task" value="0" required>
                            <input type="hidden" name="supply_id" id="supply-id" required>
                            <input type="hidden" name="balance" id="balance" value="0" required>
                            <input type="hidden" name="total_balance" id="total-balance" value="0" required>
                            <input type="hidden" name="plant_id" id="plant-id" value="{{$plant->id}}" required>
                            <input type="hidden" name="user_id" id="user-id" value="{{auth()->user()->id}}" required>
                            <button type="reset" class="btn btn-danger rounded-0 m-1">
                                Reset
                            </button>
                            <button type="submit" class="btn btn-success rounded-0 m-1">
                                Submit
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function (e) {

            var baseurl = window.location.href;

            $('#form').submit(function (e) {
                e.preventDefault();
                var data = new FormData(this);
                $.ajax({
                    url: baseurl,
                    type: 'POST',
                    method: 'POST',
                    data: data,
                    processData: false,
                    contentType: false,
                    cache: false,
                    dataType: 'JSON',
                    beforeSend: function (e) {
                        Swal.fire({
                            icon: 'info',
                            title: null,
                            text: 'Please Wait!...',
                            allowOutsideClick: false,
                            showConfirmButton: false,
                            timerProgressBar: false,
                            didOpen: function () {
                                Swal.showLoading();
                                $('small').empty();
                                $('.form-control').removeClass('form-control-danger');
                                $('button[type="submit"], button[type="reset"]').prop('disabled', true);
                            }
                        });
                    },
                }).done(function (data, status, xhr) {
                    $('#form')[0].reset();
                    swal('success', null, data.message);
                    Turbolinks.visit(data.redirect,{action: 'advance'});
                }).fail(function (data, status, xhr) {
                    const errors = data.responseJSON.errors;

                    $.map(errors, function (data, key) {
                        $('input[name="'+(key)+'"]').addClass('form-control-danger').next('small').text(data[0]);
                    });

                    $('button[type="submit"], button[type="reset"]').prop('disabled', false);
                    Swal.close();
                });
            });

            $('#supply').on('input', function (e) {
                var value = $(this).val();
                var regex = /^(.){1,}$/;

                if(!value.match(regex)){
                    $(this).addClass('form-control-danger').next('small').text(capitalize('please fill out this field'));
                    return true;
                }

                $(this).removeClass('form-control-danger').next('small').empty();
            });

            $('#price').on('input', function (e) {
                var value = $(this).val();
                var regex = /^([0-9]){1,}$/;

                if(!value.match(regex)){
                    $(this).addClass('form-control-danger').next('small').text(capitalize('please fill out this field'));
                    return true;
                }

                computation();
                $(this).removeClass('form-control-danger').next('small').empty();
            });

            $('#quantity').on('input', function (e) {
                var value = $(this).val();
                var regex = /^([0-9]){1,}$/;

                if(!value.match(regex)){
                    $(this).addClass('form-control-danger').next('small').text(capitalize('please fill out this field'));
                    return true;
                }

                computation();
                $(this).removeClass('form-control-danger').next('small').empty();
            });

            $('#total').on('input', function (e) {
                var value = $(this).val();
                var regex = /^([0-9]){1,}$/;

                if(!value.match(regex)){
                    $(this).addClass('form-control-danger').next('small').text(capitalize('please fill out this field'));
                    return true;
                }

                computation();
                $(this).removeClass('form-control-danger').next('small').empty();
            });

            $('#remarks').on('input', function (e) {
                var value = $(this).val();
                var regex = /^(.){1,}$/;

                if(!value.match(regex)){
                    $(this).addClass('form-control-danger').next('small').text(capitalize('please fill out this field'));
                    return true;
                }

                $(this).removeClass('form-control-danger').next('small').empty();
            });

            $('#task').change(function (e) {
                var checked = $(this).prop('checked');
                $('#is-task').val(Number(checked));
            });

            function computation() {
                var price = parseFloat($('#price').val());
                var quantity = parseFloat($('#quantity').val());
                var total = quantity * price;
                $('#total').val(total);
            }

            function getSuppliesList() {
                $.ajax({
                    url:mainurl+'supplies/getSuppliesList',
                    type: 'GET',
                    method: 'GET',
                    dataType: 'JSON',
                    beforeSend:function (e) {
                        $('#supply').prop('disabled', true);
                    },
                }).done(function (data, status, xhr) {
                    $('#supply').autocomplete({
                        delay: 100,
                        minLength: 2,
                        autoFocus: true,
                        source: function (request, response) {
                            response($.map(data, function (data, key) {
                                var name = data.supply.toUpperCase();
                                if (name.indexOf(request.term.toUpperCase()) !== -1) {
                                    return {
                                        key: parseInt(data.id),
                                        label: data.supply,
                                        price: parseFloat(data.price),
                                    }
                                } else {
                                    return null;
                                }
                            }));
                        },
                        create: function (event, ui) {
                            $.ui.autocomplete.prototype._renderItem = function (ul, item) {
                                var label = item.label.replace(new RegExp("(?![^&;]+;)(?!<[^<>]*)(" + $.ui.autocomplete.escapeRegex(this.term) + ")(?![^<>]*>)(?![^&;]+;)", "gi"), "<strong>$1</strong>");
                                return $('<li></li>')
                                    .data('item.autocomplete', item)
                                    .append('<li>'+(label)+'</li>')
                                    .appendTo(ul);
                            };
                        },
                        focus: function(e, ui) {
                            e.preventDefault();
                        },
                        select: function(e, ui) {
                            $('#supply').val(ui.item.label);
                            $('#supply-id').val(parseInt(ui.item.key));
                            $('#price, #total').val(parseFloat(ui.item.price));
                            $('#quantity').val(1);
                            computation();
                        },
                        change: function(e, ui ) {
                            e.preventDefault();
                        },
                    }).prop('disabled', false);
                }).fail(function (data, status, xhr) {
                    Swal.close();
                });
            }

            getSuppliesList();

        });
    </script>

@endsection